"""Add vote counts to Post and create PostVoteLog table

Revision ID: 4c7179cab0a8
Revises: 5ed36c8a22a5
Create Date: 2025-05-11 11:07:20.094615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7179cab0a8'
down_revision: Union[str, None] = '5ed36c8a22a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_vote_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('UPVOTE', 'DOWNVOTE', name='votetypeenum_sqlalchemy'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_vote_uc')
    )
    op.create_index(op.f('ix_post_vote_logs_id'), 'post_vote_logs', ['id'], unique=False)
    op.add_column('posts', sa.Column('upvotes', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('downvotes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'downvotes')
    op.drop_column('posts', 'upvotes')
    op.drop_index(op.f('ix_post_vote_logs_id'), table_name='post_vote_logs')
    op.drop_table('post_vote_logs')
    # ### end Alembic commands ###
