"""Added Chat Tables

Revision ID: 639104352515
Revises: f8106e0b855f
Create Date: 2025-05-14 19:15:05.119604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639104352515'
down_revision: Union[str, None] = 'f8106e0b855f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_anonymous_room_id'), 'chat_rooms', ['anonymous_room_id'], unique=True)
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_message_id', sa.UUID(), nullable=False),
    sa.Column('chatroom_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('sender_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_anonymous_id'], ['chat_rooms.anonymous_room_id'], ),
    sa.ForeignKeyConstraint(['sender_anonymous_id'], ['users.anonymous_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_anonymous_message_id'), 'chat_messages', ['anonymous_message_id'], unique=True)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('chat_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_request_id', sa.UUID(), nullable=False),
    sa.Column('requester_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('requestee_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('initial_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='chatrequeststatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requestee_anonymous_id'], ['users.anonymous_id'], ),
    sa.ForeignKeyConstraint(['requester_anonymous_id'], ['users.anonymous_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_requests_anonymous_request_id'), 'chat_requests', ['anonymous_request_id'], unique=True)
    op.create_index(op.f('ix_chat_requests_id'), 'chat_requests', ['id'], unique=False)
    op.create_table('chatroom_participants',
    sa.Column('chatroom_id', sa.UUID(), nullable=False),
    sa.Column('user_anonymous_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chat_rooms.anonymous_room_id'], ),
    sa.ForeignKeyConstraint(['user_anonymous_id'], ['users.anonymous_id'], ),
    sa.PrimaryKeyConstraint('chatroom_id', 'user_anonymous_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatroom_participants')
    op.drop_index(op.f('ix_chat_requests_id'), table_name='chat_requests')
    op.drop_index(op.f('ix_chat_requests_anonymous_request_id'), table_name='chat_requests')
    op.drop_table('chat_requests')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_anonymous_message_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_anonymous_room_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
