"""added reports and blocks

Revision ID: d22d86491836
Revises: 639104352515
Create Date: 2025-05-19 00:55:53.313581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22d86491836'
down_revision: Union[str, None] = '639104352515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_report_id', sa.UUID(), nullable=False),
    sa.Column('reporter_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('reported_item_type', sa.Enum('USER', 'POST', 'COMMENT', name='reporteditemtypeenum_sqlalchemy'), nullable=False),
    sa.Column('reported_item_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED_ACTION_TAKEN', 'REVIEWED_NO_ACTION', 'DISMISSED', name='reportstatusenum_sqlalchemy'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_anonymous_id'], ['users.anonymous_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_anonymous_report_id'), 'reports', ['anonymous_report_id'], unique=True)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('user_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('target_anonymous_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('MUTE', 'BLOCK', name='relationshiptypeenum_sqlalchemy'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_anonymous_id'], ['users.anonymous_id'], ),
    sa.ForeignKeyConstraint(['target_anonymous_id'], ['users.anonymous_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_anonymous_id', 'target_anonymous_id', 'relationship_type', name='uq_actor_target_relationship_type')
    )
    op.create_index(op.f('ix_user_relationships_id'), 'user_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_relationships_id'), table_name='user_relationships')
    op.drop_table('user_relationships')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_anonymous_report_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
